mongodb:
  image: tozd/meteor-mongodb:2.6
  environment:
    MONGODB_ADMIN_PWD: jvkcWfymeivM3ZBZ
    MONGODB_CREATE_PWD: jvkcWfymeivM3ZBZ
    MONGODB_OPLOGGER_PWD: jvkcWfymeivM3ZBZ
meteor:
  build: .
  environment:
    ROOT_URL: "http://localhost"
    MONGO_URL: "mongodb://meteor:jvkcWfymeivM3ZBZ@mongodb/meteor"
    MONGO_OPLOG_URL: "mongodb://oplogger:jvkcWfymeivM3ZBZ@mongodb/local?authSource=admin"
  ports:
    - "3000:3000"
  links:
    - mongodb

